IF NOT EXISTS(SELECT TOP(1) 1 FROM [production].[territories])
BEGIN
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'01581', N'Westboro', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'01730', N'Bedford', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'01833', N'Georgetow', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'02116', N'Boston', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'02139', N'Cambridge', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'02184', N'Braintree', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'02903', N'Providence', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'03049', N'Hollis', 3)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'03801', N'Portsmouth', 3)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'06897', N'Wilton', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'07960', N'Morristown', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'08837', N'Edison', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10019', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10038', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10047', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10048', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10049', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10050', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10051', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10052', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10053', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10054', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10055', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10056', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10057', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10058', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10059', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10060', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10061', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10062', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10063', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10064', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10065', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10066', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10067', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10068', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10069', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10070', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10071', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10072', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10073', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10074', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10075', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10076', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10077', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10078', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10079', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10080', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10081', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10082', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10083', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10084', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10085', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10086', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10087', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10088', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10089', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10090', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10091', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10092', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10093', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10094', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10095', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10096', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10097', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10098', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10099', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10100', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10101', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10102', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10103', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10104', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10105', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10106', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10107', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10108', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10109', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10110', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10111', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10112', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10113', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10114', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10115', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10116', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10117', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10118', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10119', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10120', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10121', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10122', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10123', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10124', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10125', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10126', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10127', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10128', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10129', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10130', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10131', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10132', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10133', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10134', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10135', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10136', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10137', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10138', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10139', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10140', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10141', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10142', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10143', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10144', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10145', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10146', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10147', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10148', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10149', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10150', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10151', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10152', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10153', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10154', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10155', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10156', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10157', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10158', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10159', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10160', N'New York', 1)
    INSERT [production].[territories] ([TerritoryID], [TerritoryDescription], [RegionID]) VALUES (N'10161', N'New York', 1)

END
GO