CREATE TABLE [dbo].[DimCustomer] (
    [CustomerKey]      INT            IDENTITY(1,1) NOT NULL,
    [CustomerID_NK]    NCHAR(5)       NOT NULL,
    [CompanyName]      NVARCHAR(40)   NOT NULL,
    [ContactName]      NVARCHAR(30)   NULL,
    [ContactTitle]     NVARCHAR(30)   NULL,
    [Address]          NVARCHAR(60)   NULL,
    [City]             NVARCHAR(15)   NULL,
    [Region]           NVARCHAR(15)   NULL,
    [PostalCode]       NVARCHAR(10)   NULL,
    [Country]          NVARCHAR(15)   NULL,
    [Phone]            NVARCHAR(24)   NULL,
    [Fax]              NVARCHAR(24)   NULL,
    [CustomerTypeID]   NCHAR(10)      NULL,
    [CustomerTypeDesc] NVARCHAR(MAX)  NULL,
    [CustomerSegment]  VARCHAR(20)    NULL,
    [FirstOrderDate]   DATE           NULL,
    [LastOrderDate]    DATE           NULL,
    [TotalOrders]      INT            NULL,
    [LifetimeValue]    MONEY          NULL,
    [IsActive]         BIT            NULL,
    [CreatedDate]      DATETIME       NULL,
    [UpdatedDate]      DATETIME       NULL,
    CONSTRAINT [PK_DimCustomer] PRIMARY KEY CLUSTERED ([CustomerKey] ASC)
);