CREATE TABLE [staging].[Orders] (
    [OrderID]        INT      NOT NULL,
    [CustomerID]     NCHAR(5) NULL,
    [EmployeeID]     INT      NULL,
    [OrderDate]      DATETIME NULL,
    [RequiredDate]   DATETIME NULL,
    [ShippedDate]    DATETIME NULL,
    [ShipVia]        INT      NULL,
    [Freight]        MONEY    NULL,
    [ShipName]       NVARCHAR(40) NULL,
    [ShipAddress]    NVARCHAR(60) NULL,
    [ShipCity]       NVARCHAR(15) NULL,
    [ShipRegion]     NVARCHAR(15) NULL,
    [ShipPostalCode] NVARCHAR(10) NULL,
    [ShipCountry]    NVARCHAR(15) NULL,
    [RowVersion]     BIGINT   NOT NULL,
    [CreatedDate]    DATETIME DEFAULT GETDATE(),
    [ModifiedDate]   DATETIME DEFAULT GETDATE(),
    CONSTRAINT [PK_StagingOrders] PRIMARY KEY CLUSTERED ([OrderID] ASC)
);